# Fix theme contrast
#set-face global   PrimarySelection black,blue+F
#set-face global SecondarySelection black,green+F
#set-face global     MenuForeground black,blue
#set-face global     MenuBackground black,white
#set-face global           MenuInfo black

# Nicer colorscheme
#colorscheme plain

evaluate-commands %sh{
    gray="rgb:#{ return conf.scheme.base02 '_hex' }"
    red="rgb:#{ return conf.scheme.base08 '_hex' }"
    green="rgb:#{ return conf.scheme.base0B '_hex' }"
    yellow="rgb:#{ return conf.scheme.base0A '_hex' }"
    blue="rgb:#{ return conf.scheme.base0D '_hex' }"
    purple="rgb:#{ return conf.scheme.base0E '_hex' }"
    aqua="rgb:#{ return conf.scheme.base0C '_hex' }"
    orange="rgb:#{ return conf.scheme.base09 '_hex' }"

    bg="rgb:#{ return conf.scheme.base00 '_hex' }"
    bg_alpha="rgba:#{ return conf.scheme.base00 '_hex' }a0"
    bg1="rgb:#{ return conf.scheme.base01 '_hex' }"
    bg2="rgb:#{ return conf.scheme.base02 '_hex' }"
    bg3="rgb:#{ return conf.scheme.base03 '_hex' }"
    bg4="rgb:#{ return conf.scheme.base03 '_hex' }"

    fg="rgb:#{ return conf.scheme.base05 '_hex' }"
    fg_alpha="rgba:#{ return conf.scheme.base05 '_hex' }a0"
    fg0="#{ return conf.scheme.base04 '_hex' }"
    fg2="#{ return conf.scheme.base04 '_hex' }"
    fg3="rgb:#{ return conf.scheme.base06 '_hex' }"
    fg4="rgb:#{ return conf.scheme.base07 '_hex' }"

    echo "
        # Code highlighting
        face global value         ${purple}
        face global type          ${yellow}
        face global variable      ${blue}
        face global module        ${green}
        face global function      ${fg}
        face global string        ${green}
        face global keyword       ${red}
        face global operator      ${fg}
        face global attribute     ${orange}
        face global comment       ${gray}+i
        face global documentation comment
        face global meta          ${aqua}
        face global builtin       ${fg}+b

        # Markdown highlighting
        face global title     ${green}+b
        face global header    ${orange}
        face global mono      ${fg4}
        face global block     ${aqua}
        face global link      ${blue}+u
        face global bullet    ${yellow}
        face global list      ${fg}

        face global Default            ${fg},${bg}
        face global PrimarySelection   ${fg_alpha},${blue}+g
        face global SecondarySelection ${bg_alpha},${blue}+g
        face global PrimaryCursor      ${bg},${fg}+fg
        face global SecondaryCursor    ${bg},${bg4}+fg
        face global PrimaryCursorEol   ${bg},${fg4}+fg
        face global SecondaryCursorEol ${bg},${bg2}+fg
        face global LineNumbers        ${bg4}
        face global LineNumberCursor   ${yellow},${bg1}
        face global LineNumbersWrapped ${bg1}
        face global MenuForeground     ${bg2},${blue}
        face global MenuBackground     ${fg},${bg2}
        face global MenuInfo           ${bg}
        face global Information        ${bg},${fg}
        face global Error              ${bg},${red}
        face global DiagnosticError    ${red}
        face global DiagnosticWarning  ${yellow}
        face global StatusLine         ${fg},${bg}
        face global StatusLineMode     ${yellow}+b
        face global StatusLineInfo     ${purple}
        face global StatusLineValue    ${red}
        face global StatusCursor       ${bg},${fg}
        face global Prompt             ${yellow}
        face global MatchingChar       ${fg},${bg3}+b
        face global BufferPadding      ${bg2},${bg}
        face global Whitespace         ${bg2}+f
    "
}

define-command reload "source #{ return os.getenv('HOME') }/.config/kak/kakrc"

# Add line numbers
add-highlighter global/ln number-lines -relative -hlcursor -separator "  " -min-digits 3
set-face global LineNumberCursor yellow,default,default

# Whitespaces
add-highlighter global/ws show-whitespaces

# Put statusbar on top
#set global ui_options terminal_status_on_top=true

# Highlight all search matches
add-highlighter global/search dynregex '%reg{/}' 0:+b

# Add soft-wrapping
#add-highlighter global/wrap wrap -word -indent -width 80 -marker ' -> '

# Show soft-limit column
add-highlighter global/lim column 80 default,black+d

# Make cursor yellow on Insert mode
hook global BufCreate .* %{
    hook buffer ModeChange (push|pop):insert:.* %{
        set-face buffer PrimaryCursor black,white
    }
    hook buffer ModeChange (push|pop):.*:insert %{
        set-face buffer PrimaryCursor black,yellow
    }
}

# Fix indenting
hook global WinSetOption filetype=(?!makefile).* %{
    map global insert <tab> '<a-;><a-gt>'
    map global insert <s-tab> '<a-;><a-lt>'
}

# Fix go identing
hook global WinSetOption filetype=go|a %{
    set buffer indentwidth 0
    set buffer tabstop 4
}

# Start LSP
eval %sh{kak-lsp}
lsp-enable
lsp-inlay-diagnostics-enable global
lsp-inlay-hints-enable global

# Custom bindings
map global user l ":enter-user-mode lsp<ret>" -docstring "lsp mode"
